greatnonprofits-nfp/rapidpro

- temba/contacts/views.py
- templates/contacts/contact_history.haml
- templates/contacts/contact_read.haml
to make easier the communication 1 <> 1 between our users with their customers, we change the way to send direct messages accessing contact information. We removed the Send Message option from the settings and added a message box just below the contact fields.
> Send message box (chat style)

- static/less/legacy.less
This PR fixes this ticket: 
_Issue: Icons sometimes don't fit in the main navbar_ (https://app.asana.com/0/1152254835058569/1154898118646940/f)
> Fix nav bar width

- temba/orgs/models.py
- temba/orgs/views.py
- temba/utils/templatetags/temba.py
- templates/orgs/org_parse_data_import.haml
- templates/partials/split_editor.haml
This PR includes fixes for Gift Card feature:
1. Active column value is not updated after complete Gift Card flow [https://app.asana.com/0/1152254835058569/1153479080091217/f](https://app.asana.com/0/1152254835058569/1153479080091217/f)
2. Unable to import data with Unicode character on .csv file [https://app.asana.com/0/1152254835058569/1153566369564539/f](https://app.asana.com/0/1152254835058569/1153566369564539/f)
3. Unable to import XLS/XLSX file that Saved as from .CSV file [https://app.asana.com/0/1152254835058569/1154005071836169/f](https://app.asana.com/0/1152254835058569/1154005071836169/f)
4. Incorrect behavior on cancelling import Giftcard data [https://app.asana.com/0/1152254835058569/1153479080091223/f](https://app.asana.com/0/1152254835058569/1153479080091223/f)
5. Legacy …
> Feature/parse integration 2.0

- temba/links/models.py
- temba/orgs/models.py
- templates/smartmin/base.html
1. Issue: Importing a flow (with trackable links) created from old platform does not automatically import/create the trackable links too https://app.asana.com/0/1152050780796838/1154452898724538/f
> Feature/trackable links 2.0

- static/coffee/flows/controllers.coffee
- static/coffee/flows/widgets.coffee
- templates/partials/json_directive.haml
- templates/partials/split_editor.haml
Task https://app.asana.com/0/1159876841343611/1170302825643337/f
> Feature: JSON Request body

- templates/flows/flow_editor_next.haml
Task https://app.asana.com/0/1152254835058569/1156484700437394/f
Task https://app.asana.com/0/1152254835058569/1156511709693627/f
> Export to PDF bug fixes.

- temba/orgs/models.py
- temba/orgs/tests.py
Task https://app.asana.com/0/1159876841343611/1171619451194923/f
> Alert when the credits are low

- temba/campaigns/migrations/0036_auto_20200402_1534.py
- temba/contacts/views.py
- temba/flows/views.py
- temba/mixins.py
- temba/msgs/migrations/0141_auto_20200402_1534.py
- temba/orgs/migrations/0059_usersettings_authy_id.py
- temba/orgs/models.py
- temba/orgs/tasks.py
- temba/orgs/views.py
- templates/contacts/contact_list.haml
Task https://app.asana.com/0/1152254835058569/1171990666500198/f
> Bug: Internal Server Error when accessing deleted or non-existent contact group pages

- temba/campaigns/migrations/0034_merge_20200313_1149.py
- temba/campaigns/migrations/0035_auto_20200313_1150.py
- temba/campaigns/migrations/0036_auto_20200402_1534.py
- temba/channels/views.py
- temba/contacts/views.py
- temba/flows/migrations/0226_merge_20200313_1155.py
- temba/flows/models.py
- temba/flows/tests.py
- temba/flows/views.py
- temba/links/migrations/0002_auto_20200123_1321.py
- temba/links/models.py
- temba/msgs/migrations/0139_merge_20200313_1155.py
- temba/msgs/migrations/0140_auto_20200317_1558.py
- temba/msgs/migrations/0141_auto_20200402_1534.py
- temba/msgs/tests.py
- temba/orgs/models.py
- temba/orgs/tasks.py
- temba/orgs/views.py
- temba/utils/models.py
Task: https://app.asana.com/0/1152254835058569/1172364547402577/f
> Bug: Linked flows title

- static/js/temba.js
- temba/contacts/models.py
Task: https://app.asana.com/0/0/1173176847712865/f
Task: https://app.asana.com/0/0/1173199760906306/f
> Block contact import: Bug fixes

- temba/flows/models.py
Task: https://app.asana.com/0/0/1175501782894398/f
> Fix on download images page for outer media root

- temba/contacts/models.py
- temba/flows/migrations/0229_auto_20200511_2018.py
- temba/flows/migrations/0230_flowimage_is_active.py
- temba/flows/models.py
- temba/orgs/models.py
- temba/orgs/views.py
Task: https://app.asana.com/0/1159876841343611/1172633243922187/f
> Bug: Parse cannot upload data if contains special characters

- temba/orgs/views.py
- templates/orgs/org_parse_data_import.haml
Task: https://app.asana.com/0/1159876841343611/1172633243922177/f
> Bug: Numeric data are not imported if it's formatted to have thousand separator (,)

- temba/contacts/models.py
- temba/contacts/views.py
- templates/contacts/contact_read.haml
Task: https://app.asana.com/0/1159876841343611/1172747145070647/f
> Bug: Issues on upcoming scheduled flows.

- templates/contacts/contact_invite_participants.haml
https://app.asana.com/0/1159876841343611/1158809372498665/f
> Bug: Fixed pagination on invite participants page.

- templates/flows/flow_editor_next.haml
Task: https://app.asana.com/0/1152254835058569/1156511709693627/f
> Added different colour styles on export flow to PDF

- temba/api/v2/serializers.py
- temba/api/v2/urls.py
- temba/api/v2/views.py
- temba/flows/migrations/0229_auto_20200511_2018.py
- temba/flows/migrations/0230_flowimage_is_active.py
- temba/flows/models.py
- templates/flows/flow_editor_next.haml
Task: https://app.asana.com/0/1159876841343611/1158544836278234/f
> Bug: Url attachment validation on email attachments page

- temba/contacts/views.py
- temba/orgs/views.py
- templates/frame.haml
- templates/orgs/org_giftcards.haml
- templates/orgs/org_parse_data_import.haml
Task: https://app.asana.com/0/1159876841343611/1152050780796883/f
> Bug: Giftcard issues

- temba/contacts/views.py
- temba/flows/models.py
Task: https://app.asana.com/0/1159876841343611/1152483606380666/f
> Legacy flow import fix

- temba/orgs/views.py
Task: https://app.asana.com/0/1159876841343611/1172633243922177/f
> Bugfix: Refactored parse data import

- temba/flows/views.py
Issue: https://app.asana.com/0/0/1178482176781923/f
> Remove downoad images functional from phone and surveyor flows

- temba/channels/views.py
- temba/flows/views.py
- temba/orgs/views.py
- temba/settings_common.py
- temba/utils/__init__.py
- templates/flows/flow_editor_next.haml
- templates/flows/flow_export_pdf.haml
Issue: https://app.asana.com/0/1159876841343611/1152481332340153/f
> Styles fixing for export flow to PDF

- temba/channels/models.py
Issue: https://app.asana.com/0/1159876841343611/1172381037876947/f
> Bug: Channel sending alert

- temba/orgs/views.py
Task: https://app.asana.com/0/1159876841343611/1172633243922177/f
> Bug: Numeric import fixes

- temba/channels/models.py
- templates/channels/email/sms_alert.html
- templates/channels/email/sms_alert.txt
Task: https://app.asana.com/0/1159876841343611/1172381037876947/f
> Channel alert sending

- templates/flows/flow_editor_next.haml
Task: https://app.asana.com/0/1159876841343611/1152481332340153/f
> Fix in export flow as image

- static/js/labels.js
- temba/flows/views.py
- templates/channels/email/sms_alert.html
- templates/channels/email/sms_alert.txt
- templates/flowimages/flowimage_list.haml
Issue: https://app.asana.com/0/1152254835058569/1179721335133834/f
Issue: https://app.asana.com/0/1152254835058569/1179721335133830/f
Issue: https://app.asana.com/0/1159876841343611/1172381037876947/f
> Bug: QA issues

- static/js/flow-parameters.js
- temba/flows/views.py
- templates/triggers/trigger_update.haml
This fixes the issues:
https://app.asana.com/0/1159876841343611/1176946675695579
https://app.asana.com/0/1159876841343611/1181818105256262
> Fix flow params

- temba/msgs/views.py
- templates/campaigns/campaign_read.haml
- templates/flows/flow_editor_next.haml
Issue: https://app.asana.com/0/1152254835058569/1177321926797281/f
Issue: https://app.asana.com/0/1152254835058569/1175838248516402/f
Issue: https://app.asana.com/0/1152254835058569/1177374802711833/f
> Fixing QA issues

- temba/orgs/context_processors.py
- templates/campaigns/campaignevent_read.haml
- templates/flows/flow_editor_next.haml
Issue: https://app.asana.com/0/1152254835058569/1177692064703425/f
Issue: https://app.asana.com/0/1152254835058569/1177374802711833/f
Issue: https://app.asana.com/0/1159876841343611/1176079434805145/f
Issue: https://app.asana.com/0/1152254835058569/1177321926797281/f
> Bug: Resolving QA issues

- temba/msgs/views.py
Bug: https://app.asana.com/0/1159876841343611/1182109875173649/f
> Bug: Fixing unique validation for folders and labels according to soft deletion

- temba/flows/views.py
- temba/links/models.py
- temba/links/views.py
Task: https://app.asana.com/0/1159876841343611/1178914902629969/f
> Bug: Flow related links

- temba/flows/views.py
- temba/links/views.py
- templates/links/link_read.haml
Issue: https://app.asana.com/0/0/1182950553249131/f
Issue: https://app.asana.com/0/0/1182950553245129/f
Issue: https://app.asana.com/0/0/1182751635804626/f
> Bug: Trackable link bug fixes for archived flows

- package.json
- temba/flows/models.py
- temba/flows/views.py
Issue: https://app.asana.com/0/0/1183082285204051/f
Issue: https://app.asana.com/0/0/1183097109416947/f
> Bug: Spell checker 2.0

- temba/flows/models.py
Issue: https://app.asana.com/0/0/1182978730979505/f
> Bug: Add links to flow results export

- templates/flowimages/flowimage_list.haml
Issue: https://app.asana.com/0/1152254835058569/1183521605554137/f
> Issue: Image thumbnails column on Flow Images pages is hidden in lower screen size.

- temba/flows/merging.py
- temba/flows/migrations/0232_mergeflowstask.py
- temba/flows/models.py
- temba/flows/views.py
- templates/flows/email/flow_merging_result.html
- templates/flows/email/flow_merging_result.txt
- templates/flows/flow_editor_next.haml
- templates/flows/flow_merge_flows.haml
- templates/flows/flow_merge_modal.haml
Issue: https://app.asana.com/0/0/1185629900856340/f
Issue: https://app.asana.com/0/0/1185629900856344/f
Issue: https://app.asana.com/0/0/1185620293215382/f
> Bug: Flow merging

- temba/flows/models.py
- templates/flows/email/flow_merging_error.html
- templates/flows/email/flow_merging_error.txt
Bug: https://app.asana.com/0/0/1185791116339913/f
> Bug: Fixing issue with saving merging metadata

- docker/docker.settings
- temba/migrator/models.py
- temba/orgs/tasks.py
https://app.asana.com/0/1177482227268314/1188662518716690
> Parse data migration

- package.json
- temba/api/v2/serializers.py
- temba/api/v2/urls.py
- temba/api/v2/views.py
- temba/flows/merging/merging.py
- templates/flows/flow_editor_next.haml
Issue: https://app.asana.com/0/1159876841343611/1186094551686811/f
Related PR: https://github.com/greatnonprofits-nfp/floweditor/pull/55
> Issue: Using 'Wait for Response' input same as 'Trigger word' in a flow

- temba/flows/merging/merging.py
- temba/flows/views.py
Bug: https://app.asana.com/0/0/1186840644813538/f
> Bug: Merge Flows 

- temba/flows/merging/serializers.py
Bug: https://app.asana.com/0/0/1186840644813538/f
> BUG: (Merge Flow) Fix for accessing None instance origin node

- temba/contacts/views.py
Issue: https://app.asana.com/0/1152254835058569/1183888778907351/f
> Issue: 'Single Message' flows display in the contact field uses

- package.json
- temba/flows/views.py
- temba/links/models.py
Issue: https://app.asana.com/0/1159876841343611/1185750108109221/f
> Issue: Alert for mistyped trackable links

- temba/links/models.py
Issue: https://app.asana.com/0/0/1193329833984291/f
Issue: https://app.asana.com/0/0/1193329833961289/f
> Bug: Issues in mistyped trackable links

- temba/flows/merging/merging.py
Issue: https://app.asana.com/0/0/1186840644813538/f
> BUG: Fixed merge flow issues

- temba/flows/merging/merging.py
- temba/flows/views.py
- templates/flows/flow_merge_flows.haml
Issue: https://app.asana.com/0/0/1194597144220267/f
> Bug: Merge Flow Issue

- templates/flows/flow_merge_flows.haml
Issue: https://app.asana.com/0/0/1194597144220267/f
> Bug: Merge flows label issue

- temba/orgs/views.py
Issue: https://app.asana.com/0/1152254835058569/1193971975598509/f
> Bug: Mistyping fixed

- temba/api/v2/serializers.py
- temba/api/v2/urls.py
- temba/api/v2/views.py
- temba/flows/views.py
- temba/links/models.py
- temba/triggers/models.py
- templates/flows/flow_editor_next.haml
- templates/flows/flow_export_pdf.haml
To do not force users to edit the response rules containing trigger words to save Wait for Response changes I have moved that chanking to the issues tab. And now I do check on backend side.
Bug: https://app.asana.com/0/0/1196600343863397/f
Related Frontend PR: https://github.com/greatnonprofits-nfp/floweditor/pull/65
> Bug: Keyword trigger rule

- temba/channels/types/external/type.py
Bug: https://app.asana.com/0/1159876841343611/1198172849224697/f
> Bug: Fixed access to External API Channel configuration page

- temba/campaigns/views.py
- templates/utils/forms/completion_textarea.haml
Issue: https://app.asana.com/0/1152254835058569/1178255620258169/f
> Bug: Fixed rp-completion endpoints

- temba/flows/models.py
- temba/flows/tasks.py
- temba/settings_common.py
Ticket: https://app.asana.com/0/0/1199149605913149/f
> Bug: Merge flows task

- temba/links/models.py
- temba/links/views.py
- temba/orgs/views.py
Issue: https://app.asana.com/0/1152254835058569/1152522895908034/f
Issue: https://app.asana.com/0/1152254835058569/1152522895330030/f
> Bug: Trackable link issues

- temba/flows/models.py
- temba/flows/tasks.py
- templates/flows/flow_merging_flows_table.haml
Issue: https://app.asana.com/0/0/1199180312551899/f
+ Improvements (refactored transferring of flow_runs, path_counts and exit_counts)
> Issue: Flow merging

- temba/flows/merging/merging.py
- temba/flows/merging/test_data.py
- temba/flows/models.py
1. Changed flow step matching algorithm.
2. Fixed bug with transferring the last chunk of flow runs.
> Feature: Flow merging

- templates/contacts/contact_list.haml
Feature: https://app.asana.com/0/1159876841343611/1183783967515474/f
> Feature: Ability to View Group Memberships of Contacts

- temba/contacts/models.py
Ticket: https://app.asana.com/0/1159876841343611/1197085650681345/f
> Feature: Include Contact Groups in Contact Export

- templates/contacts/contact_list.haml
Issue: https://app.asana.com/0/1159876841343611/1183783967515474/f
> Bug: Fixed contact group flickering on contacts page

- temba/flows/tasks.py
- temba/settings_common.py
Issue: https://app.asana.com/0/1152254835058569/1181121442350122/f
> Bug: Image thumbnail not created for .gif image type

- temba/flows/merging/test_data.py
Issue: https://app.asana.com/0/1159876841343611/1199508297484503/f
> Bug: Merge flows

- temba/api/v2/urls.py
- temba/api/v2/views.py
https://app.asana.com/0/1159876841343611/1199520473062485/f
> Feature: Parse Server API Endpoint

- docker/docker.settings
- pip-freeze.txt
- pip-requires.txt
- temba/settings_common.py
- temba/temba_celery.py
Ticket: https://app.asana.com/0/1159876841343611/1199694500406392/f
> Sentry SDK update

- temba/contacts/views.py
- templates/contacts/contact_invite_participants.haml
Issue: https://app.asana.com/0/1152254835058569/1152522773369112/f
Issue: https://app.asana.com/0/0/1199881033695063/f
> Bug: Contacts pages issues

- temba/contacts/templatetags/contacts.py
- temba/contacts/views.py
- templates/contacts/contact_invite_participants.haml
Issue: https://app.asana.com/0/1152254835058569/1152522773369112/f
> Bug: Filtering contacts with no connection on invite participants page.

- templates/contacts/contact_list.haml
Ticket: https://app.asana.com/0/1159876841343611/1199912816732852/f
> Feature: Select all contacts

- temba/campaigns/views.py
- temba/triggers/views.py
- temba/utils/__init__.py
- templates/campaigns/campaignevent_update.haml
- templates/triggers/trigger_list.haml
- templates/triggers/trigger_update.haml
It includes:
[Issue] [Triggers] Triggers for flows with flow parameters do not have the label " | Contains flow parameters" on Triggers page [https://app.asana.com/0/1159876841343611/1200099377983975](https://app.asana.com/0/1159876841343611/1200099377983975)
[Issue] [Flow Parameters] Flow parameter fields on campaign event does not update when the flow parameter variable was removed or added to the flow [https://app.asana.com/0/1159876841343611/1200099377983980](https://app.asana.com/0/1159876841343611/1200099377983980)
[Issue] [Flow Parameters] Saved value in flow parameter field containing comma [https://app.asana.com/0/1159876841343611/1200100163976534](https://app.asana.com/0/1159876841343611/1200100163976534)
[Issue] [Campaigns] No default selected option for flow starting rule on …
> Fixes for v3

- temba/campaigns/views.py
- temba/globals/views.py
- temba/orgs/views.py
- temba/triggers/views.py
- templates/links/link_list.haml
- templates/public/public_index.haml
[Issue] [Flow Parameters] User is able to update triggers or add/update flow campaign events with empty Flow Parameters
https://app.asana.com/0/0/1200110928181060/f
[Issue] [Trackable Link] The position of checkbox, trackable link name, clicks columns is not fixed
https://app.asana.com/0/0/1200115869397853/f
[Issue] [Homepage] Splash image covers alert message displayed on the homepage
https://app.asana.com/0/0/1200109716060727/f
[Issue] [Globals] 'Single Message' flows are included in the list of flows on Global Details modal
https://app.asana.com/0/0/1200113775569779/f
[Issue] [Topups] Deleted orgs still appear in the 'From Workspace' and 'To Workspace' dropdown on Transfer Credits modal
https://app.asana.com/0/0/1200113775569780/f
> Fix: Issues on v3

- temba/channels/views.py
- templates/channels/channellog_list.haml
Ticket: https://app.asana.com/0/1159876841343611/1198983753330667/f
> Feature: Filter Errors in Message Log

- temba/api/v2/views.py
- templates/api/v2/api_explorer.haml
- templates/flows/flow_results.haml
- templates/includes/flatpickr_field.haml
Issue: Messages Report: Change names in the results
https://app.asana.com/0/0/1200151125756194/f
Issue: API Explorer for the Reports do not have Query String input boxes to add parameter to generate CSV file
https://app.asana.com/0/0/1200151125756181/f
Issue: Flow Report: Documentation and API explorer edits
https://app.asana.com/0/0/1200151125756200/f
Issue: Messages Report: Documentation and API explorer edits
https://app.asana.com/0/0/1200151125756197/f
Issue: Contacts Report: Some filters not implemented
https://app.asana.com/0/0/1200142651448118/f
Issue: Trackable Link Report: Filters group name(s)/UUID(s), before, and after are not implemented
https://app.asana.com/0/0/1200151125756176/f
Issue: Unable to filter by "contact_urn" with value as "tel:" …
> Fixes: Reports API issues.

- temba/api/v2/views.py
- temba/contacts/search/elastic.py
- temba/flows/views.py
- temba/triggers/models.py
- templates/api/v2/api_explorer.haml
- templates/flows/flow_results.haml
Copying/Creating a flow step with error using the mouse right-click
https://app.asana.com/0/1159876841343611/1200159103971794/f
Issue: Filtering  flow results by before or after<date>on Runs tab
https://app.asana.com/0/0/1200176098496218/f
Issue: Unable to display more columns after filtering flow results on Runs tab
https://app.asana.com/0/0/1200175217079125/f
Issue: Sentry error when searching flow results by non-existent contact fields
https://app.asana.com/0/0/1200175217079128/f
Issue: Contacts Report: Get Body Fields section on API Explorer should be updated to show the other available fields to use to query
https://app.asana.com/0/0/1200175217079119/f
Issue: Contacts Report: Sending invalid request body does not return 4XX status and 'detail' message …
> Fixes: Issues with report endpoints and runs filtering.

- temba/channels/types/dialog360/views.py
- temba/channels/types/line/views.py
- temba/channels/types/signalwire/views.py
- templates/flows/flow_results.haml
Issue: Submitting SignalWire and Dialog350 add channel forms with blank input fields causes 500 internal server error
https://app.asana.com/0/1159876841343611/1200113775569783/f
Issue: Page switches back to 'Responded' runs after clicking Filter button when viewing the 'All' runs
https://app.asana.com/0/0/1200215878757745/f
Issue: Unable to filter the flow results by Last Activity time
https://app.asana.com/0/0/1200215827835313/f
> Fixes: QA issues.

- temba/api/v2/views.py
- temba/contacts/management/commands/update_es_with_flows_channels.py
- temba/contacts/tasks.py
- temba/settings_common.py
Ticket: https://app.asana.com/0/0/1200185701317189/f
> Improvements: Elasticsearch indexing for channels and flows

- temba/api/v2/views.py
- temba/orgs/views.py
Defect: Only up to 1000 rows are displayed on Gift Card/Lookup Collection Preview page
https://app.asana.com/0/1159876841343611/1172633243922179/f
> Feature: Pagination on collection preview page.

- temba/flows/views.py
- temba/msgs/views.py
- temba/public/templatetags/json.py
- templates/utils/forms/contact_search.haml
Issue: Server errors revealed by Sentry
https://app.asana.com/0/1159876841343611/1200252852550883/f
> BugFix: Sentry issues

- temba/api/v2/views.py
- temba/contacts/tasks.py
Issue: Bad Gateway on Flow Variable Report when it has more than one variable on the query
https://app.asana.com/0/0/1200406377591734/f
Issue: Flow Report: 504 Gateway Timeout error when querying a flow with lots of runs
https://app.asana.com/0/0/1200347585363354/f
> Bugfix: QA issues

- temba/api/v2/views.py
- temba/flows/views.py
Issue: Flow Report: 504 Gateway Timeout error when querying a flow with lots of runs
https://app.asana.com/0/0/1200422827528447/f
https://app.asana.com/0/0/1200347585363354/f
Issue: Trackable Link Report: Update the API documentation and explorer to include details and example on how to filter by group name(s) OR UUID(s), before, and after
https://app.asana.com/0/0/1200347585363343/f
Issue: Unable to filter run by Contact Fields of archived, blocked, stopped and deleted contacts
https://app.asana.com/0/0/1200365637456616/f
> Bugfix: Report issues.

- temba/api/v2/views.py
Issue: Flow Report: 504 Gateway Timeout error when querying a flow with lots of runs
https://app.asana.com/0/0/1200347585363354/f
> Improvements for Flow Report Endpoints

- temba/api/v2/views.py
Issue: Flow Report: 504 Gateway Timeout error when querying a flow with lots of runs
https://app.asana.com/0/0/1200347585363354/f
Issue: Contacts Report: 500 Internal Server error
https://app.asana.com/0/0/1200435803434338/f
Issue: Contacts Report: Inaccurate total_unique_contacts returned when filtered by flow
https://app.asana.com/0/0/1200347585363352/f
> QA issues fixes

- temba/api/v2/views.py
- temba/flows/models.py
- temba/links/tasks.py
- temba/triggers/views.py
- templates/triggers/trigger_catchall.haml
- templates/triggers/trigger_create.haml
- templates/triggers/trigger_list.haml
- templates/triggers/trigger_missed_call.haml
- templates/triggers/trigger_new_conversation.haml
- templates/triggers/trigger_referral.haml
- templates/triggers/trigger_update.haml
Issue: No Flow Parameters input fields shown when a flow with flow param variables is selected when creating certain triggers
https://app.asana.com/0/1159876841343611/1200490570277142/f
Issue: No data in export file when exporting filtered run results that have blocked/archived/stopped contacts
https://app.asana.com/0/1159876841343611/1200491647855341/f
Issue: LinkContacts.MultipleObjectsReturned
https://app.asana.com/0/1159876841343611/1200506364130193/f
Issue: Add extra validator with explanation to flow variables report.
https://app.asana.com/0/1159876841343611/1200505561493612/f
> Fixes: Triggers flow params & Filtered results export.

- temba/api/v2/views.py
Investigate query on messages reporting API
https://app.asana.com/0/1159876841343611/1200543029414275/f
Issue: API contact_report timeout
https://app.asana.com/0/1159876841343611/1200554489663788/f
> Improvements: Messages report and contact report endpoints

- temba/api/v2/views.py
- temba/contacts/views.py
- temba/urls.py
Issue: Issues that appeared in sentry logs
https://app.asana.com/0/1159876841343611/1200565026215384/f
Issue: API contact_report timeout
https://app.asana.com/0/1159876841343611/1200554489663788/f
> Fixes: Sentry log issues

- docker/docker.settings
- temba/api/v2/views.py
- temba/settings_common.py
Investigate query on messages reportintg API
https://app.asana.com/0/1159876841343611/1200543029414275/f
Issue: API contact_report timeout
https://app.asana.com/0/1159876841343611/1200554489663788/f
> Improvements: Reporting API

- temba/api/v2/views.py
Issue: API contact_report timeout
https://app.asana.com/0/1159876841343611/1200554489663788/f
> Improvements: Contact report endpoints.

- temba/api/v2/serializers.py
- temba/api/v2/views.py
Add flow_variable to Reporting API 
https://app.asana.com/0/1200625938047469/1200610781381065/f
> Feature: Flow variables report

- package.json
- temba/reports/tasks.py
- temba/reports/views.py
- temba/settings_common.py
Issue: [Analytics] Unable to search flow by name
https://app.asana.com/0/0/1200802393865985/f
Issue: [Analytics] Viewer user is unable to access /report/analytics/ page
https://app.asana.com/0/0/1200802393865988/f
Issue: [Analytics] Flows without any steps are still shown at /report/analytics/ page
https://app.asana.com/0/0/1200802393865979/f
> Fixes: Analytics Dashboard

- package.json
Issue: Missing setting options at analytics flow list page
https://app.asana.com/0/0/1200971083075013/f
> Improvement: Gear button on analytics flows page.

- temba/reports/models.py
- temba/reports/tasks.py
- temba/reports/views.py
[Dashboard Analytics] No data is shown after adding flow and can not continue to add other flows
https://app.asana.com/0/1152254835058569/1200990262697359/f
> Fix for analytics dashboard synchronization.

- temba/orgs/tests.py
- temba/orgs/views.py
Back Translation to Confirm Accuracy of Translations Input
https://app.asana.com/0/1200626743215615/1201058156248705/f
Added unittests and fixed the issue with not being able to set up an API key.
> Feature: Back translations. Improvements.

- templates/contacts/contact_read.haml
- templates/msgs/message_box.haml
- templates/triggers/trigger_schedule_in_batch.haml
Issue: Warning popup is not shown when trigger a flow in batches
https://app.asana.com/0/0/1201484679348998/f
Issue: Clicking "Cancel" then clicking "Confirm" button sends duplicate messages
https://app.asana.com/0/0/1201484679348990/f
> Feature: Do not contact fixes

- templates/flows/flow_editor.haml
Issue: Clicking "Cancel" then clicking "Confirm" button sends duplicate messages
https://app.asana.com/0/0/1201484679348990/f
> Feature: Do not contact (QA Issues)

- code_check.py
- temba/channels/migrations/0129_auto_20211103_1310.py
- temba/channels/views.py
- temba/flows/legacy/migrations.py
- templates/channels/channel_read.haml
1. Issue: Incoming segments are counting to outgoing segments - https://app.asana.com/0/0/1201470853745513/f
2. Issue: Discrepancies between mockup and app - https://app.asana.com/0/0/1201473409707425/f
> Fixes for Report by Segments feature

- temba/orgs/tests.py
- temba/orgs/views.py
https://app.asana.com/0/1200626743215615/1201527356339499/f
> restored managing users in org update form

- temba/flows/views.py
- templates/flows/flow_results.haml
- templates/flows/flow_run_table.haml
https://app.asana.com/0/1200626743215615/1201527356339493/f
> Show up the number of results found on the runs filter functionality

- temba/archives/tests.py
- temba/orgs/tests.py
- temba/orgs/views.py
https://app.asana.com/0/1200626743215615/1201527356339485/f
> hide unused org menus

- templates/channels/channelevent_calls.haml
https://app.asana.com/0/1200626743215615/1201527356339489/f
> fixed duplicate pagination

- templates/channels/channelevent_calls.haml
https://app.asana.com/0/1200626743215615/1201527356339489/f
> fixed overlapping shadow

- temba/channels/types/kaleyra/type.py
- temba/contacts/models.py
- temba/flows/views.py
- temba/msgs/views.py
- temba/utils/languages.py
https://app.asana.com/0/1202104348045775/1202084700210011/f
https://app.asana.com/0/1202104348045775/1202084454900554/f
https://app.asana.com/0/1202104348045775/1202084702013571/f
https://app.asana.com/0/1202104348045775/1202084702013574/f
https://app.asana.com/0/1202104348045775/1202084702013577/f
https://app.asana.com/0/1202104348045775/1202084702013577/f
https://app.asana.com/0/1202104348045775/1202098148019158/f
> Fix 5.0 QA feedback

- temba/orgs/views.py
- templates/includes/nav.haml
Bug: Unable to import data to a Lookup collection
https://app.asana.com/0/1202104348045775/1202113855970193/f
> Fix: Fixed issue with pandas on lookup import

- temba/contacts/views.py
- temba/utils/models.py
Bug: After searching for contacts in Archive and using Delete All function, archived contacts don't disappear immediately.
https://app.asana.com/0/1202035323216759/1202061285286808/f
> BugFix: Fixed issue with deleted contact after search

- temba/api/v2/serializers.py
- temba/api/v2/tests.py
- temba/api/v2/urls.py
- temba/api/v2/views.py
- temba/settings_common.py
- temba/tests/twilio.py
Phone Number Validation API
https://app.asana.com/0/1200626743215615/1202143695272016/f
> Feature: Phone Validation API

- temba/api/v2/tests.py
- temba/api/v2/views.py
Phone Number Validation API
https://app.asana.com/0/1200626743215615/1202143695272016/f
> Fix: Changed Twilio phone validation endpoint to use POST method

- temba/msgs/views.py
https://app.asana.com/0/1202104348045775/1202098211330399/f
> added option to remove folder selection for labels

- temba/campaigns/views.py
- templates/campaigns/campaign_list.haml
Bug: Archived campaign searching turns into active campaign searching
https://app.asana.com/0/0/1202164986502670/f
> Fix/5.0 QA feedback

- temba/contacts/models.py
- temba/flows/views.py
- temba/orgs/models.py
- temba/urls.py
- temba/utils/s3/s3.py
- temba/utils/s3/views.py
[HIPPA] An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
https://app.asana.com/0/1202035323216759/1202005566653494/f
> Fix: Private AWS S3 bucket

- temba/assets/models.py
No email was received when trying to download flow results
https://app.asana.com/0/0/1202187395496556/f
> Fix: Refactored assets object to return public s3 link.

- temba/api/v2/tests.py
- temba/api/v2/urls.py
- temba/api/v2/views.py
Phone Number Validation API
https://app.asana.com/0/1200626743215615/1202143695272016/f
https://github.com/greatnonprofits-nfp/rapidpro/pull/293#issuecomment-1122469021
> (Update) Hide mention of Twilio in the Phone Validation Endpoint.

- temba/contacts/tasks.py
- temba/contacts/tests.py
- temba/settings_common.py
- temba/utils/email.py
- temba/utils/tests.py
- templates/contacts/email/deactivated_contacts_email.html
- templates/contacts/email/deactivated_contacts_email.txt
Auto-Opt Out Phone Numbers that are on the Carrier Deactivation List
https://app.asana.com/0/1200626743215615/1202135747268378/f
> Feature: Auto opt out

- temba/orgs/models.py
- temba/orgs/views.py
Change from count to usage + get int value from usage format number
> Hotfix Twilio Usage

- temba/contacts/tasks.py
- temba/orgs/tasks.py
https://sentry.io/organizations/greatnonprofits/issues/3427392715/?referrer=slack
https://sentry.io/organizations/greatnonprofits/issues/3328883761/?referrer=slack
> Fix: CC Bugs

- static/js/formax.js
- temba/channels/views.py
- templates/flows/flow_editor.haml
- templates/flows/flow_export_pdf.haml
https://communityconnectlabs.atlassian.net/browse/CD-154
https://communityconnectlabs.atlassian.net/browse/CD-155
https://communityconnectlabs.atlassian.net/browse/CD-156
> Fix: Merge issues

- temba/utils/templatetags/temba.py
- templates/orgs/login/login.haml
- templates/smartmin/users/login.haml
https://communityconnectlabs.atlassian.net/browse/CD-151?atlOrigin=eyJpIjoiOGFkMGU5YTAwMzlhNGY3ZDk3ODU0N2QxNGI2MmVjNWUiLCJwIjoiaiJ9
> Fix: XSS Protection

- temba/contacts/models.py
- temba/flows/models.py
- temba/orgs/models.py
https://communityconnectlabs.atlassian.net/browse/CD-174
> fix org deletion issues

- temba/campaigns/views.py
- temba/flows/views.py
- templates/contacts/contact_list_include.haml
https://communityconnectlabs.atlassian.net/browse/CD-78?focusedCommentId=10451
> Fix for monitoring dashboard

- temba/contacts/migrations/0145_auto_20221107_1150.py
- temba/contacts/views.py
- temba/links/migrations/0006_alter_linkcontacts_flow.py
- temba/msgs/migrations/0163_alter_msg_status.py
- temba/settings_common.py
- templates/contacts/contact_read.haml
https://communityconnectlabs.atlassian.net/jira/software/projects/CD/boards/3?selectedIssue=CD-84
> [BugFix] Campaign log showing to an user that will not receive it

- .pre-commit-config.yaml
- templates/msgs/message_box.haml
https://communityconnectlabs.atlassian.net/browse/CD-219
> Feature: Msg select all

- templates/msgs/message_box.haml
https://communityconnectlabs.atlassian.net/browse/CD-219
> Fixed "Select All" button

- docker/docker.settings
- temba/context_processors.py
- temba/settings_common.py
- templates/orgs/login/login.haml
- templates/smartmin/users/login.haml
- templates/smartmin/users/user_forget.haml
Reference: https://communityconnectlabs.atlassian.net/jira/software/projects/CD/boards/3?selectedIssue=CD-181
> Remove reCaptcha from login/forget password forms

- templates/msgs/message_box.haml
https://communityconnectlabs.atlassian.net/jira/software/projects/CD/boards/3?selectedIssue=CD-219
> Fix 'Select all' button on label change

- temba/notifications/models.py
- templates/notifications/email/export_finished.links.html
- templates/notifications/email/export_finished.links.txt
Reference: https://communityconnectlabs.atlassian.net/jira/software/projects/CD/boards/3?selectedIssue=CD-220
> Add email template on exporting trackable links

- static/js/msg-encodings.js
- templates/campaigns/campaign_read.haml
- templates/campaigns/campaignevent_read.haml
- templates/campaigns/campaignevent_update.haml
- templates/utils/forms/segments_counter.haml
https://communityconnectlabs.atlassian.net/browse/CD-28
> Better encoding display and replacement - campaigns

- temba/campaigns/views.py
- templates/campaigns/campaign_read.haml
- templates/campaigns/campaignevent_read.haml
https://communityconnectlabs.atlassian.net/jira/software/projects/CD/boards/3?selectedIssue=CD-28
> (Fix) duplicated fields

- temba/classifiers/views.py
- templates/classifiers/classifier_train.haml
- templates/classifiers/replacements_message.haml
https://communityconnectlabs.atlassian.net/browse/CD-26
> Feature: Classifier encoding replacement

- media/flow_editor/gsm7-replacements.json
- temba/classifiers/types/dialogflow/train_bot.py
- temba/utils/gsm7.py
- templates/classifiers/classifier_train.haml
- templates/classifiers/replacements_message.haml
Reference: https://communityconnectlabs.atlassian.net/jira/software/projects/CD/boards/3?selectedIssue=CD-26
> Fix issues on the text replacement

- temba/channels/templatetags/channels.py
- temba/channels/types/webchat/views.py
- temba/channels/views.py
- templates/channels/channel_update.haml
- templates/channels/types/webchat/config.haml
https://communityconnectlabs.atlassian.net/jira/software/projects/CD/boards/3?selectedIssue=CD-279
> Added WebChat option to store history

- temba/flows/tests.py
- temba/flows/views.py
https://communityconnectlabs.atlassian.net/jira/software/projects/CD/boards/3?selectedIssue=CD-313
> IVR retry field to voice flow creation

- temba/contacts/models.py
https://communityconnectlabs.atlassian.net/jira/software/projects/CD/boards/3?selectedIssue=CD-257
> Feature: Handle groups creation on contacts importation

- temba/contacts/models.py
- temba/contacts/templatetags/contacts.py
- temba/contacts/tests.py
- temba/mailroom/events.py
- templates/contacts/contact_history.haml
Include the retry call log on the contact history
https://communityconnectlabs.atlassian.net/jira/software/projects/CD/boards/3?selectedIssue=CD-310
Related PR: https://github.com/greatnonprofits-nfp/mailroom/pull/61
> Feature: Retry call logs
